#include "web_server.h"
#include "esp_wifi.h"
#include "esp_mac.h"
#include "esp_log.h"
#include "esp_event.h"
#include "nvs_flash.h"
#include "esp_http_server.h"
#include "network.h"
#include "packet.h"
#include <string.h>

static const char *TAG = "WEB_SERVER";
static httpd_handle_t server = NULL;

// Declare the embedded text files (symbols generated by linker)
extern const uint8_t index_html_start[] asm("_binary_index_html_start");
extern const uint8_t index_html_end[]   asm("_binary_index_html_end");
extern const uint8_t style_css_start[]  asm("_binary_style_css_start");
extern const uint8_t style_css_end[]    asm("_binary_style_css_end");
extern const uint8_t app_js_start[]     asm("_binary_app_js_start");
extern const uint8_t app_js_end[]       asm("_binary_app_js_end");

/* HTTP GET Handlers for Static Files */
static esp_err_t index_html_handler(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/html");
    size_t size = index_html_end - index_html_start;
    httpd_resp_send(req, (const char*)index_html_start, size);
    return ESP_OK;
}

static esp_err_t style_css_handler(httpd_req_t *req) {
    httpd_resp_set_type(req, "text/css");
    size_t size = style_css_end - style_css_start;
    httpd_resp_send(req, (const char*)style_css_start, size);
    return ESP_OK;
}

static esp_err_t app_js_handler(httpd_req_t *req) {
    httpd_resp_set_type(req, "application/javascript");
    size_t size = app_js_end - app_js_start;
    httpd_resp_send(req, (const char*)app_js_start, size);
    return ESP_OK;
}

/* WebSocket Server Handler */
static esp_err_t ws_handler(httpd_req_t *req) {
    if (req->method == HTTP_GET) {
        ESP_LOGI(TAG, "Handshake completed, new WS Client connected.");
        return ESP_OK;
    }

    httpd_ws_frame_t ws_pkt;
    uint8_t *buf = NULL;
    memset(&ws_pkt, 0, sizeof(httpd_ws_frame_t));
    ws_pkt.type = HTTPD_WS_TYPE_BINARY;

    // Get payload size
    esp_err_t ret = httpd_ws_recv_frame(req, &ws_pkt, 0);
    if (ret != ESP_OK) {
        ESP_LOGE(TAG, "Failed to parse websocket frame size");
        return ret;
    }

    if (ws_pkt.len > 0) {
        buf = (uint8_t*)calloc(1, ws_pkt.len + 1);
        if (buf == NULL) {
            ESP_LOGE(TAG, "Out of memory for websocket packet data");
            return ESP_ERR_NO_MEM;
        }
        ws_pkt.payload = buf;
        ret = httpd_ws_recv_frame(req, &ws_pkt, ws_pkt.len);
        if (ret != ESP_OK) {
            ESP_LOGE(TAG, "Failed to receive websocket frame payload");
            free(buf);
            return ret;
        }

        // Parse note packet (3 bytes: [Status, NoteNumber, Velocity])
        if (ws_pkt.len == 3) {
            uint8_t status = buf[0];
            uint8_t note = buf[1];
            uint8_t velocity = buf[2];

            ESP_LOGD(TAG, "WS Msg: Status=0x%02X, Note=%d, Vol=%d", status, note, velocity);

            // Translate message into ESP-NOW PianoDataPacket
            PianoDataPacket espNowPacket;
            memset(&espNowPacket, 0, sizeof(PianoDataPacket));

            if (status == 0x90 && velocity > 0) {
                espNowPacket.noteCount = 1;
                espNowPacket.activeNotes[0] = note;
                espNowPacket.overallAmplitude = velocity;
            } else {
                espNowPacket.noteCount = 0; // Note off
                espNowPacket.activeNotes[0] = 0;
                espNowPacket.overallAmplitude = 0;
            }

            // Broadcast note to ESP_lights over ESP-NOW!
            Network.broadcast(espNowPacket);
        }
        free(buf);
    }
    return ESP_OK;
}

/* WebSocket Broadcast Back to Browser */
void web_server_send_midi_packet(uint8_t status, uint8_t note, uint8_t velocity) {
    if (server == NULL) return;

    size_t max_fds = 8;
    int fds[8] = {0};
    esp_err_t ret = httpd_sess_get_fds(server, &max_fds, fds);
    if (ret != ESP_OK) return;

    uint8_t buf[3] = { status, note, velocity };
    httpd_ws_frame_t ws_pkt;
    memset(&ws_pkt, 0, sizeof(httpd_ws_frame_t));
    ws_pkt.payload = buf;
    ws_pkt.len = 3;
    ws_pkt.type = HTTPD_WS_TYPE_BINARY;

    for (size_t i = 0; i < max_fds; i++) {
        // Send data directly to connected websockets
        httpd_ws_send_data(server, fds[i], &ws_pkt);
    }
}

/* Start Server */
void start_web_server(void) {
    httpd_config_t config = HTTPD_DEFAULT_CONFIG();
    
    // Allow WebSocket protocol handling
    config.ctrl_port = 32768; 

    ESP_LOGI(TAG, "Starting HTTP/WS Server on Port 80...");
    if (httpd_start(&server, &config) == ESP_OK) {
        
        // 1. Register Index Route
        httpd_uri_t index_uri = {
            .uri       = "/",
            .method    = HTTP_GET,
            .handler   = index_html_handler,
            .user_ctx  = NULL
        };
        httpd_register_uri_handler(server, &index_uri);

        // 2. Register CSS Route
        httpd_uri_t css_uri = {
            .uri       = "/style.css",
            .method    = HTTP_GET,
            .handler   = style_css_handler,
            .user_ctx  = NULL
        };
        httpd_register_uri_handler(server, &css_uri);

        // 3. Register JS Route
        httpd_uri_t js_uri = {
            .uri       = "/app.js",
            .method    = HTTP_GET,
            .handler   = app_js_handler,
            .user_ctx  = NULL
        };
        httpd_register_uri_handler(server, &js_uri);

        // 4. Register WebSocket Route
        httpd_uri_t ws_uri = {
            .uri        = "/ws",
            .method     = HTTP_GET,
            .handler    = ws_handler,
            .user_ctx   = NULL,
            .is_websocket = true
        };
        httpd_register_uri_handler(server, &ws_uri);

        ESP_LOGI(TAG, "Web Server routes registered successfully.");
    } else {
        ESP_LOGE(TAG, "Failed to start HTTP server!");
    }
}

/* Initialise Wi-Fi AP Mode */
void wifi_init_softap(void) {
    esp_err_t ret = esp_netif_init();
    if (ret != ESP_OK && ret != ESP_ERR_INVALID_STATE) {
        ESP_ERROR_CHECK(ret);
    }
    ret = esp_event_loop_create_default();
    if (ret != ESP_OK && ret != ESP_ERR_INVALID_STATE) {
        ESP_ERROR_CHECK(ret);
    }

    esp_netif_create_default_wifi_ap();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    wifi_config_t wifi_config = {};
    strcpy((char*)wifi_config.ap.ssid, "Piano-Guide-AP");
    wifi_config.ap.ssid_len = strlen("Piano-Guide-AP");
    wifi_config.ap.channel = 1;
    wifi_config.ap.max_connection = 4;
    wifi_config.ap.authmode = WIFI_AUTH_OPEN; // Passwordless for easy hackathon connection

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_AP));
    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP, &wifi_config));
    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_LOGI(TAG, "=============================================");
    ESP_LOGI(TAG, "Wi-Fi Hotspot Started: SSID='Piano-Guide-AP'");
    ESP_LOGI(TAG, "Connect phone/laptop and visit http://192.168.4.1");
    ESP_LOGI(TAG, "=============================================");
}
